-- DROP TABLE TEST
-- CREATE TABLE TEST  
-- (  
--  id_num int IDENTITY(1,1),  
--  fname varchar (20),  
--  minit char(1),  
--  lname varchar(30)  
-- );  
  
-- INSERT TEST  
--    (fname, minit, lname)  
-- VALUES  
--    ('Karin', 'F', 'Josephs');  
  
-- SELECT * FROM TEST
-- DROP TABLE Contact_Us
-- DROP TABLE TEST
-- SELECT table_name FROM information_schema.tables
-- CREATE TABLE Accounts (ID int IDENTITY(1,1), Email varchar(max),User_Name varchar(max), Password varchar(max))
-- SELECT * FROM Accounts
-- CREATE TABLE Contact_Us (ID int IDENTITY(1,1),  Email varchar(max),Question varchar(max))
-- CREATE TABLE Accounts (ID int IDENTITY(1,1), Email varchar(max),User_Name varchar(max), Password varchar(max))
-- DROP TABLE Accounts
-- DROP TABLE Contact_Us
-- SELECT * FROM Accounts
-- SELECT * FROM Contact_Us